"""On parent ``Stop`` event, post a short summary + "View full" link.

The silencer suppresses the generic status-bubble update on Stop (no
more *"✓ Ready"* / *"✓ Done — summary"* status messages with their
``[Esc][📸][Last][Get File]`` keyboard). This module's wrapper replaces
that with a single clean, layer-owned message:

- One short summary line generated by ``ccgram.llm.summarizer`` (the
  same one ccgram uses for status bubbles).
- One inline-URL button → ``/view/<share_token>`` on the cloudflared
  tunnel, where the full assistant turn renders as a phone-friendly
  HTML page.

When the LLM is unavailable, the summary falls back to a static
"Done — view full turn" so the user always gets the link.

Subagent Stop events are ignored (the layer waits for the parent's
Stop), matching the design note in ``handlers/hook_events.py``.
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any

import structlog

from .. import state
from ..config import load_settings
from ..share.links import make_share_url
from ..share.store import save_share
from .silencer import _is_silent_for_window

logger = structlog.get_logger()

# Module-level guard so re-running ``install_summarizer`` from tests
# does not double-wrap ``_handle_stop``.
_installed = False

# Icon-only labels — text gets clipped on mobile, so the action row is glyphs.
# 📄 = full turn (URL), 🆚 = diff/compare (URL), ⚙️ = settings (callback, from
# settings_panel.button_for_window). URL buttons also show Telegram's ↗ hint.
_BUTTON_LABEL = "📄"


def _build_keyboard(
    *, link_url: str | None, diff_url: str | None, window_id: str | None
) -> Any:
    """Build the View-full / Diff / Settings action row (or None when empty)."""
    # Lazy: PTB types pulled in only on the actual send path.
    from telegram import InlineKeyboardButton, InlineKeyboardMarkup

    row: list[InlineKeyboardButton] = []
    if link_url:
        row.append(InlineKeyboardButton(_BUTTON_LABEL, url=link_url))
    if diff_url:
        row.append(InlineKeyboardButton("🆚", url=diff_url))
    if window_id:
        # Lazy: settings_panel installs alongside; import at send time.
        from ..settings_panel import button_for_window

        # Lazy: scenarios installs alongside; import at send time.
        from ..scenarios import scenarios_button_for_window

        # 🎬 Scenarios sits just before ⚙️ Settings on the action row.
        row.append(scenarios_button_for_window(window_id))
        row.append(button_for_window(window_id))
    return InlineKeyboardMarkup([row]) if row else None


async def _post_summary_message(
    *,
    client: Any,
    chat_id: int,
    thread_id: int | None,
    summary: str,
    link_url: str | None,
    diff_url: str | None = None,
    window_id: str | None = None,
) -> int | None:
    """Post the Stop summary IN FULL — split across messages, no truncation.

    The action buttons (View full · View diff · Settings) ride only the LAST
    chunk. Returns that last chunk's message id (so the caller can strip its
    keyboard on the next turn), or ``None`` if nothing sent.
    """
    # Lazy: entity-safe sender handles markdown→plain fallback + splitting.
    from ccgram.handlers.messaging_pipeline.message_sender import safe_send

    # Lazy: 4096-char splitter.
    from ccgram.telegram_sender import split_message

    keyboard = _build_keyboard(
        link_url=link_url, diff_url=diff_url, window_id=window_id
    )
    chunks = split_message(summary) or ["✅ Done."]
    last_id: int | None = None
    for idx, chunk in enumerate(chunks):
        is_last = idx == len(chunks) - 1
        sent = await safe_send(
            client,
            chat_id,
            chunk,
            message_thread_id=thread_id,
            reply_markup=keyboard if is_last else None,
            disable_notification=True,  # silent ping — user is reading
        )
        if is_last and sent is not None:
            last_id = sent.message_id
    return last_id


async def _strip_prior_summary_buttons(bot: Any, entries: list[dict[str, int]]) -> None:
    """Remove inline keyboards from prior turns' summary messages.

    Tolerates BadRequest (message too old / already gone / not modified) so a
    stale id never aborts the new turn's post.
    """
    if bot is None:
        return
    # Lazy: only needed in this branch.
    import contextlib

    # Lazy: PTB error types only needed on the send path.
    from telegram.error import TelegramError

    for entry in entries:
        with contextlib.suppress(TelegramError):
            await bot.edit_message_reply_markup(
                chat_id=entry["chat_id"],
                message_id=entry["message_id"],
                reply_markup=None,
            )


async def _maybe_save_diff_snapshots(*, window_id: str, bot_token: str) -> str | None:
    """Freeze this turn's working tree as the next snapshot. Return the diff URL.

    Resolves the repo via the workspace-aware ``resolve_repo`` (so clone/worktree
    sessions snapshot the right tree, not the original project). The capture is
    serialized per-window so two racing Stops can't both write iteration N. On a
    non-git workspace the GitOpError is swallowed and no diff link is offered.
    """
    # Lazy: deferred to avoid a heavy/cyclic import at module load.
    from ..git_ops import capture_snapshot

    # Lazy: deferred to avoid a heavy/cyclic import at module load.
    from ..git_ops._run import GitOpError

    # Lazy: deferred to avoid a heavy/cyclic import at module load.
    from ..share.links import _miniapp_base_url

    # Lazy: deferred to avoid a heavy/cyclic import at module load.
    from ..share.tokens import sign_share_token

    repo = state.resolve_repo(window_id)
    if not repo:
        return None

    try:
        async with state.transaction(window_id):
            entry = await asyncio.to_thread(
                capture_snapshot, window_id=window_id, project_root=repo
            )
            sidecar = state.load(window_id)
            if sidecar is not None:
                sidecar.last_snapshot_id = entry.commit_sha
                if entry.n == 0:
                    sidecar.session_anchor_sha = entry.commit_sha
                state.save(sidecar)
    except (GitOpError, ValueError) as exc:
        logger.debug("diff snapshot capture failed for %s: %s", window_id, exc)
        return None

    base = _miniapp_base_url()
    if not base:
        return None
    token = sign_share_token(bot_token=bot_token, share_id=window_id)
    return f"{base.rstrip('/')}/diff/{token}"


def _extract_last_assistant_text_and_tool_count(
    transcript_path: str,
) -> tuple[str, int]:
    """Return ``(last_assistant_text, tool_use_count)`` for the most recent turn.

    Walks the JSONL backwards from EOF, collecting assistant text until
    it hits the previous ``user`` boundary; counts ``tool_use`` blocks
    that appeared in the same turn so the summarizer can decide whether
    Claude's response is "brief and self-contained" vs "did real work".
    """
    try:
        lines = (
            Path(transcript_path)
            .read_text(encoding="utf-8", errors="replace")
            .splitlines()
        )
    except OSError:
        return "", 0
    text_chunks: list[str] = []
    tool_count = 0
    for raw_line in reversed(lines[-400:]):
        try:
            entry = json.loads(raw_line)
        except json.JSONDecodeError:
            continue
        role = entry.get("role") or entry.get("type", "")
        if role == "user":
            # Reached the boundary — stop walking back.
            break
        message = entry.get("message", {})
        if not isinstance(message, dict):
            continue
        content = message.get("content")
        if isinstance(content, list):
            for block in content:
                if not isinstance(block, dict):
                    continue
                btype = block.get("type", "")
                if btype == "text" and role == "assistant":
                    text_chunks.insert(0, block.get("text", ""))
                elif btype == "tool_use":
                    tool_count += 1
    return "\n\n".join(c.strip() for c in text_chunks if c and c.strip()), tool_count


def _resolve_bindings(window_id: str) -> list[tuple[int, int, int]]:
    """Return the bound ``(user_id, thread_id, chat_id)`` tuples for *window_id*."""
    # Lazy: thread_router is wired by ccgram bootstrap.
    from ccgram.thread_router import thread_router

    bindings: list[tuple[int, int, int]] = []
    for user_id, thread_map in thread_router.thread_bindings.items():
        for thread_id, bound_window in thread_map.items():
            if bound_window == window_id:
                chat_id = thread_router.resolve_chat_id(user_id, thread_id)
                if chat_id:
                    bindings.append((user_id, thread_id, chat_id))
    return bindings


def _build_summary_and_share(
    *, transcript_path: str, window_id: str, num_turns: int
) -> tuple[str, str]:
    """Return ``(summary_text, share_id)`` for the just-finished turn.

    Telegram shows Claude's COMPLETE plain-language summary (the TL;DR block,
    never truncated); the full technical turn is stored as structured events for
    the web "View full turn" page. If Claude omitted the TL;DR (trivial turn),
    fall back to the full last-assistant text with the Telegram-only markers
    (TL;DR + progress notes) stripped.
    """
    # Lazy: transcript_events pulls only stdlib + dataclasses.
    from .transcript_events import events_to_dicts, extract_events

    # Lazy: tldr is a pure-stdlib layer module.
    from .tldr import extract_tldr, strip_progress, strip_tldr

    last_text, _tool_count = _extract_last_assistant_text_and_tool_count(
        transcript_path
    )
    events = extract_events(transcript_path)
    share_body = json.dumps(
        {"v": 2, "num_turns": num_turns, "events": events_to_dicts(events)},
        ensure_ascii=False,
    )
    share_id = save_share(
        kind="claude-turn",
        title=f"Claude turn · {window_id}",
        body_markdown=share_body,
        window_id=window_id,
    )

    tldr = extract_tldr(last_text)
    if tldr:
        summary_text = tldr
    elif last_text:
        summary_text = strip_progress(strip_tldr(last_text)).strip()
    else:
        summary_text = "✅ Done."
    return (summary_text or "✅ Done."), share_id


async def _post_summaries_to_bindings(
    *,
    client: Any,
    bot: Any,
    window_id: str,
    bindings: list[tuple[int, int, int]],
    summary_text: str,
    link_url: str | None,
    diff_url: str | None,
    settings_window: str | None,
) -> None:
    """Strip last turn's buttons, post this turn's summary, persist its id(s)."""
    prior = state.load(window_id)
    if prior is not None and prior.last_summary_messages:
        await _strip_prior_summary_buttons(bot, prior.last_summary_messages)

    new_entries: list[dict[str, int]] = []
    for _user_id, thread_id, chat_id in bindings:
        last_id = await _post_summary_message(
            client=client,
            chat_id=chat_id,
            thread_id=thread_id,
            summary=summary_text,
            link_url=link_url,
            diff_url=diff_url,
            window_id=settings_window,
        )
        if last_id is not None:
            new_entries.append(
                {"chat_id": chat_id, "thread_id": thread_id, "message_id": last_id}
            )

    async with state.transaction(window_id):
        sidecar = state.load(window_id)
        if sidecar is not None:
            sidecar.last_summary_messages = new_entries
            state.save(sidecar)


async def _handle_stop_summary(event: Any, client: Any) -> None:
    """The layer-owned Stop handler. Reads transcript, sends one summary."""
    # Lazy: ccgram internal — deferred to avoid an import cycle with ccgram bootstrap (the layer is imported during bootstrap).
    from ccgram.window_query import view_window

    # event.window_key is "<session>:<window_id>"; window_id is the second part.
    window_key = getattr(event, "window_key", "") or ""
    if ":" not in window_key:
        return
    window_id = window_key.split(":", 1)[1]

    # Subagent Stop events also fire — match the parent-only filter used by
    # the upstream _handle_stop.
    if getattr(event, "data", None) and event.data.get("subagent", False):
        return

    if not _is_silent_for_window(window_id):
        return  # non-silent windows keep their original status bubble

    view = view_window(window_id)
    if not view or not view.transcript_path:
        return

    transcript_path = str(view.transcript_path)
    num_turns = (
        int(event.data.get("num_turns", 0))
        if hasattr(event, "data") and isinstance(event.data, dict)
        else 0
    )

    bindings = _resolve_bindings(window_id)
    if not bindings:
        return

    # Finalize the live "⚙️ Working on your request…" bubble (relabel to
    # "✅ Completed", KEEP it as a record of what Claude did) before posting the
    # final summary below it.
    # Lazy: deferred to avoid a heavy/cyclic import at module load.
    from . import progress_bubble

    bot_for_cleanup = client._bot if hasattr(client, "_bot") else None
    if bot_for_cleanup is not None:
        await progress_bubble.finalize_bubble(window_id, bot_for_cleanup)

    summary_text, share_id = _build_summary_and_share(
        transcript_path=transcript_path, window_id=window_id, num_turns=num_turns
    )

    # Lazy: config is the source of bot_token + miniapp settings.
    from ccgram.config import config

    link = make_share_url(bot_token=config.telegram_bot_token, share_id=share_id)

    # Diff snapshot: save rolling iteration anchor + first-time session
    # anchor. If save fails (non-git workspace), we just skip the diff link.
    diff_link = await _maybe_save_diff_snapshots(
        window_id=window_id, bot_token=config.telegram_bot_token
    )

    # The ⚙️ Settings button drives Claude-specific levers (/model, /effort,
    # plan mode); only attach it for Claude windows.
    settings_window = window_id if view.provider_name == "claude" else None

    await _post_summaries_to_bindings(
        client=client,
        bot=bot_for_cleanup,
        window_id=window_id,
        bindings=bindings,
        summary_text=summary_text,
        link_url=link,
        diff_url=diff_link,
        settings_window=settings_window,
    )


def install_summarizer() -> None:
    """Wrap ``hook_events._handle_stop`` so silent-mode windows get our message.

    The original handler still runs (it does broker delivery + status
    bookkeeping; only the visible status-bubble side-effect was already
    silenced upstream of this wrap). The layer's summary message is
    posted after the original returns, so we never race with the
    upstream bookkeeping.
    """
    global _installed
    if _installed:
        return

    # Lazy: hook_events is the canonical home of the Stop handler.
    from ccgram.handlers import hook_events as hook_events_mod

    original = hook_events_mod._handle_stop

    async def wrapped(event: Any, client: Any) -> None:
        await original(event, client)
        try:
            await _handle_stop_summary(event, client)
        except Exception:  # noqa: BLE001 -- summary failures must never crash bot
            logger.exception("ccgram-pro Stop summary failed")

    wrapped.__name__ = "silenced_wrapped_handle_stop"
    wrapped.__qualname__ = wrapped.__name__
    hook_events_mod._handle_stop = wrapped  # type: ignore[assignment]
    _installed = True
    logger.info(
        "ccgram-pro Stop summarizer installed — silent topics get one summary + share link"
    )


def _reset_for_testing() -> None:
    """Drop the installed flag so tests can re-install cleanly."""
    global _installed
    _installed = False


# Keep the settings reference reachable for monkey-patching in tests.
_ = load_settings, state  # noqa: B018 -- module-level usage, see future patches
