"""On parent ``Stop`` event, post a short summary + "View full" link.

The silencer suppresses the generic status-bubble update on Stop (no
more *"✓ Ready"* / *"✓ Done — summary"* status messages with their
``[Esc][📸][Last][Get File]`` keyboard). This module's wrapper replaces
that with a single clean, layer-owned message:

- One short summary line generated by ``ccgram.llm.summarizer`` (the
  same one ccgram uses for status bubbles).
- One inline-URL button → ``/view/<share_token>`` on the cloudflared
  tunnel, where the full assistant turn renders as a phone-friendly
  HTML page.

When the LLM is unavailable, the summary falls back to a static
"Done — view full turn" so the user always gets the link.

Subagent Stop events are ignored (the layer waits for the parent's
Stop), matching the design note in ``handlers/hook_events.py``.
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any

import structlog

from .. import state
from ..config import load_settings
from ..share.links import make_share_url
from ..share.store import save_share
from .silencer import _is_silent_for_window

logger = structlog.get_logger()

# Module-level guard so re-running ``install_summarizer`` from tests
# does not double-wrap ``_handle_stop``.
_installed = False

_LLM_SUMMARY_TIMEOUT_SECONDS = 5
_MAX_INLINE_TEXT_CHARS = 350
_BUTTON_LABEL = "📎 View full turn"


def _build_long_view_markdown(transcript_path: str, num_turns: int) -> str:
    """Read the most recent assistant turn out of *transcript_path*.

    The JSONL transcript stores one event per line. We walk backwards from
    EOF until we hit the *previous* user turn boundary, then return the
    concatenated text of assistant messages + tool use/result content
    that happened since.
    """
    lines: list[str] = []
    try:
        raw = Path(transcript_path).read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        logger.warning("could not read transcript %s: %s", transcript_path, exc)
        return "_(transcript unavailable)_"
    # Last 200 lines is enough — a single turn rarely produces more entries.
    for raw_line in raw.splitlines()[-200:]:
        try:
            entry = json.loads(raw_line)
        except json.JSONDecodeError:
            continue
        role = entry.get("role") or entry.get("type", "")
        message = entry.get("message", {})
        if not isinstance(message, dict):
            continue
        content = message.get("content")
        if isinstance(content, list):
            chunks = []
            for block in content:
                if not isinstance(block, dict):
                    continue
                btype = block.get("type", "")
                if btype == "text":
                    chunks.append(block.get("text", ""))
                elif btype == "thinking":
                    text = block.get("text") or block.get("thinking", "")
                    if text:
                        chunks.append(f"_thinking:_ {text}")
                elif btype == "tool_use":
                    name = block.get("name", "tool")
                    tool_input = block.get("input", {})
                    pretty = json.dumps(tool_input, indent=2, sort_keys=True)
                    chunks.append(f"**`{name}`**\n```\n{pretty}\n```")
                elif btype == "tool_result":
                    tool_content = block.get("content", "")
                    if isinstance(tool_content, list):
                        tool_content = "\n".join(
                            b.get("text", "") if isinstance(b, dict) else str(b)
                            for b in tool_content
                        )
                    chunks.append(f"_tool result:_\n```\n{tool_content}\n```")
            if chunks:
                lines.append(f"### {role}\n" + "\n\n".join(chunks))
        elif isinstance(content, str) and content:
            lines.append(f"### {role}\n{content}")
    if not lines:
        return "_(empty turn)_"
    header = (
        f"_Turn ended after {num_turns} message(s). Full transcript content below._"
    )
    return f"{header}\n\n" + "\n\n---\n\n".join(lines[-30:])


async def _safe_llm_summary(transcript_path: str) -> str | None:
    """Best-effort one-line summary via the existing ccgram LLM completer."""
    # Lazy: pulls in the LLM client; only needed inside the Stop path.
    from ccgram.llm.summarizer import summarize_completion

    try:
        return await asyncio.wait_for(
            summarize_completion(transcript_path),
            timeout=_LLM_SUMMARY_TIMEOUT_SECONDS,
        )
    except (TimeoutError, RuntimeError, OSError, ValueError):
        logger.debug("LLM summary unavailable", exc_info=True)
        return None


async def _post_summary_message(
    *,
    client: Any,
    chat_id: int,
    thread_id: int | None,
    summary: str,
    link_url: str | None,
    diff_url: str | None = None,
) -> None:
    """Send the single Stop summary message with View-full and Diff buttons."""
    # Lazy: PTB types pulled in only on the actual send path.
    from telegram import InlineKeyboardButton, InlineKeyboardMarkup
    from telegram.error import TelegramError

    buttons: list[InlineKeyboardButton] = []
    if link_url:
        buttons.append(InlineKeyboardButton(_BUTTON_LABEL, url=link_url))
    if diff_url:
        buttons.append(InlineKeyboardButton("📊 View diff", url=diff_url))
    reply_markup = InlineKeyboardMarkup([buttons]) if buttons else None
    try:
        await client.send_message(
            chat_id=chat_id,
            message_thread_id=thread_id,
            text=summary,
            reply_markup=reply_markup,
            disable_notification=True,  # silent ping — user is reading
        )
    except TelegramError as exc:
        logger.warning("failed to send Stop summary: %s", exc)


async def _maybe_save_diff_snapshots(*, window_id: str, bot_token: str) -> str | None:
    """Capture an iteration snapshot (+ session anchor if missing). Return URL."""
    # Lazy: git_ops pulls subprocess; only needed if we actually have a repo.
    from ccgram.window_query import view_window

    from ..git_ops import save_snapshot
    from ..git_ops._run import GitOpError
    from ..git_ops.snapshot import list_snapshots
    from ..share.links import _miniapp_base_url
    from ..share.tokens import sign_share_token

    view = view_window(window_id)
    if not view or not view.cwd:
        return None

    existing = list_snapshots(window_id)
    try:
        if "session" not in existing:
            save_snapshot(
                window_id=window_id, label="session", project_root=view.cwd
            )
        save_snapshot(window_id=window_id, label="iteration", project_root=view.cwd)
    except (GitOpError, ValueError) as exc:
        logger.debug("diff snapshot save failed for %s: %s", window_id, exc)
        return None

    base = _miniapp_base_url()
    if not base:
        return None
    token = sign_share_token(bot_token=bot_token, share_id=window_id)
    return f"{base.rstrip('/')}/diff/{token}"


_BRIEF_TURN_THRESHOLD_CHARS = 600


def _extract_last_assistant_text_and_tool_count(
    transcript_path: str,
) -> tuple[str, int]:
    """Return ``(last_assistant_text, tool_use_count)`` for the most recent turn.

    Walks the JSONL backwards from EOF, collecting assistant text until
    it hits the previous ``user`` boundary; counts ``tool_use`` blocks
    that appeared in the same turn so the summarizer can decide whether
    Claude's response is "brief and self-contained" vs "did real work".
    """
    try:
        lines = Path(transcript_path).read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return "", 0
    text_chunks: list[str] = []
    tool_count = 0
    for raw_line in reversed(lines[-400:]):
        try:
            entry = json.loads(raw_line)
        except json.JSONDecodeError:
            continue
        role = entry.get("role") or entry.get("type", "")
        if role == "user":
            # Reached the boundary — stop walking back.
            break
        message = entry.get("message", {})
        if not isinstance(message, dict):
            continue
        content = message.get("content")
        if isinstance(content, list):
            for block in content:
                if not isinstance(block, dict):
                    continue
                btype = block.get("type", "")
                if btype == "text" and role == "assistant":
                    text_chunks.insert(0, block.get("text", ""))
                elif btype == "tool_use":
                    tool_count += 1
    return "\n\n".join(c.strip() for c in text_chunks if c and c.strip()), tool_count


async def _handle_stop_summary(event: Any, client: Any) -> None:
    """The layer-owned Stop handler. Reads transcript, sends one summary."""
    # Lazy: thread_router is wired by ccgram bootstrap.
    from ccgram.thread_router import thread_router
    from ccgram.window_query import view_window

    # event.window_key is "<session>:<window_id>"; window_id is the second part.
    window_key = getattr(event, "window_key", "") or ""
    if ":" not in window_key:
        return
    window_id = window_key.split(":", 1)[1]

    # Subagent Stop events also fire — match the parent-only filter used by
    # the upstream _handle_stop.
    if getattr(event, "data", None) and event.data.get("subagent", False):
        return

    if not _is_silent_for_window(window_id):
        return  # non-silent windows keep their original status bubble

    view = view_window(window_id)
    if not view or not view.transcript_path:
        return

    transcript_path = str(view.transcript_path)
    num_turns = (
        int(event.data.get("num_turns", 0))
        if hasattr(event, "data") and isinstance(event.data, dict)
        else 0
    )

    # Resolve the bound (user, thread, chat) tuple.
    bindings: list[tuple[int, int, int]] = []  # (user_id, thread_id, chat_id)
    for user_id, thread_map in thread_router.thread_bindings.items():
        for thread_id, bound_window in thread_map.items():
            if bound_window == window_id:
                chat_id = thread_router.resolve_chat_id(user_id, thread_id)
                if chat_id:
                    bindings.append((user_id, thread_id, chat_id))
    if not bindings:
        return

    # Tear down the live "🔧 Working…" bubble before posting the final
    # summary message, so the user sees one clean transition.
    from . import progress_bubble

    bot_for_cleanup = None
    if hasattr(client, "_bot"):
        bot_for_cleanup = client._bot  # PTBTelegramClient wraps PTB Bot
    if bot_for_cleanup is not None:
        await progress_bubble.stop_bubble(window_id, bot_for_cleanup)

    # Extract Claude's actual text + tool-use count for the just-finished
    # turn. The summarizer's strategy depends on this:
    # - Brief reply with no tool calls → use Claude's text verbatim
    #   (no LLM hop, no garbage hallucination if the LLM has nothing to
    #   summarise — the bug from the user's "Hi! What can I help you
    #   with?" turn).
    # - Did real work (tool calls or long text) → ask the LLM for a
    #   one-line summary so the user gets a digestible message.
    last_text, tool_count = _extract_last_assistant_text_and_tool_count(
        transcript_path
    )
    is_brief_turn = tool_count == 0 and 0 < len(last_text) <= _BRIEF_TURN_THRESHOLD_CHARS

    long_markdown = _build_long_view_markdown(transcript_path, num_turns)
    share_id = save_share(
        kind="claude-turn",
        title=f"Claude turn · {window_id}",
        body_markdown=long_markdown,
        window_id=window_id,
    )

    if is_brief_turn:
        short = last_text.strip()
    else:
        summary = await _safe_llm_summary(transcript_path)
        if summary:
            short = summary.strip()
        elif last_text:
            # LLM unavailable AND Claude wrote text — fall back to the
            # first line + ellipsis to avoid the "✅ No coding activity"
            # garbage we used to post.
            first_line = last_text.splitlines()[0].strip()
            short = first_line if len(first_line) <= _MAX_INLINE_TEXT_CHARS else (
                first_line[: _MAX_INLINE_TEXT_CHARS - 1].rstrip() + "…"
            )
        else:
            short = "✅ Done."

    if len(short) > _MAX_INLINE_TEXT_CHARS:
        short = short[: _MAX_INLINE_TEXT_CHARS - 1].rstrip() + "…"

    # Lazy: config is the source of bot_token + miniapp settings.
    from ccgram.config import config

    link = make_share_url(bot_token=config.telegram_bot_token, share_id=share_id)

    # Diff snapshot: save rolling iteration anchor + first-time session
    # anchor. If save fails (non-git workspace), we just skip the diff link.
    diff_link = await _maybe_save_diff_snapshots(
        window_id=window_id, bot_token=config.telegram_bot_token
    )

    for _user_id, thread_id, chat_id in bindings:
        await _post_summary_message(
            client=client,
            chat_id=chat_id,
            thread_id=thread_id,
            summary=short,
            link_url=link,
            diff_url=diff_link,
        )


def install_summarizer() -> None:
    """Wrap ``hook_events._handle_stop`` so silent-mode windows get our message.

    The original handler still runs (it does broker delivery + status
    bookkeeping; only the visible status-bubble side-effect was already
    silenced upstream of this wrap). The layer's summary message is
    posted after the original returns, so we never race with the
    upstream bookkeeping.
    """
    global _installed
    if _installed:
        return

    # Lazy: hook_events is the canonical home of the Stop handler.
    from ccgram.handlers import hook_events as hook_events_mod

    original = hook_events_mod._handle_stop

    async def wrapped(event: Any, client: Any) -> None:
        await original(event, client)
        try:
            await _handle_stop_summary(event, client)
        except Exception:  # noqa: BLE001 -- summary failures must never crash bot
            logger.exception("ccgram-pro Stop summary failed")

    wrapped.__name__ = "silenced_wrapped_handle_stop"
    wrapped.__qualname__ = wrapped.__name__
    hook_events_mod._handle_stop = wrapped  # type: ignore[assignment]
    _installed = True
    logger.info(
        "ccgram-pro Stop summarizer installed — silent topics get one summary + share link"
    )


def _reset_for_testing() -> None:
    """Drop the installed flag so tests can re-install cleanly."""
    global _installed
    _installed = False


# Keep the settings reference reachable for monkey-patching in tests.
_ = load_settings, state  # noqa: B018 -- module-level usage, see future patches
